### PR TITLE
NOTE_000A Project setup (frontend) [DV,JL]

### LINKED ISSUE #14: NOTE_000A Project frontend setup
Frontend counterpart of the NOTE_000 ticket.

### PR DESCRIPTION
**Pull request by deveah**
Added project scaffolding for Vue.

### CODE REVIEW

**Review by R0bi7 — APPROVED** [review]
Reviewed

**Review by R0bi7 — APPROVED** [review]

**Review by R0bi7 — APPROVED** [review]
.

**Review by LedioJahaj — APPROVED** [review]
Aproved

**Review by alt-13 — APPROVED** [review]
Review done

**Comment by alt-13** [comment]
Resolves #14

**Pull request merged**
